### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by PetrSvirak** [xvasko/deepmood#1]
You're missing tests for your reducers, thunk actions, and utils functions.

To be able to write tests for the thunk actions properly, you'll need to inject their some of the functions they call in them. Use the factory pattern to achieve that. Something like this:
````
// actions/profile/fetchUserAvatar.js
export const fetchUserAvatarFactory = (dependencies) =>
  (avatarId) =>
    async (dispatch, getState) => {
      const avatarUri = await dependencies.fetchReceive(createApiFilerUri(avatarId));
      dispatch(updateProfileAvatar(avataruri));
    };
````
````
// actions/index.js
import { fetchUserAvatarFactory } from './profile/fetchUserAvatar';
import { fetchReceive } from '../../utils/api/fetchReceive';

export const fetchUserAvatar = fetchUserAvatarFactory({ fetchReceive });
````
````
// actions/profile/fetchUserAvatar.test.js
import { fetchUserAvatarFactory } from './fetchUserAvatar';

const fetchReceive = jest.fn(() => Promise.resolve());
const fetchUserAvatar = fetchUserAvatarFactory({ fetchReceive });
````

**Comment by xvasko** [comment]
resolved, did use mock-axios-adapter library for this

**Comment by PetrSvirak** [comment]
Your thunk actions' tests would be less complex if you did extract the "fetch" dependency (as described above) - if you injected the `axios` instead of importing it directly, you could avoid mocking responses to given absolute URLs. 

Also, you test your reducers twice (once when you mock store in thunk actions' tests and once in reducers' tests). It would actually be enough to inject basic actions (that can be tested alongside reducers) into thunk actions and then just test whether injected basic actions were called in the correct order for tested conditions in thunk actions' tests.

Tests could then be swifter and more unit-oriented. While your tests run all in memory, numerous mocking techniques you used, render them much closer to certain kinds of integration tests than unit tests they ought to be.
