### ISSUE TITLE
Use react lifecycle for initial load

### ISSUE THREAD

**Issue by PetrSvirak** [xvasko/deepmood#4]
Do not use `store.dispatch` directly. Use [react lifecycle](https://reactjs.org/docs/react-component.html#the-component-lifecycle) methods (read more [here](https://reactjs.org/docs/state-and-lifecycle.html) and [here](https://engineering.musefind.com/react-lifecycle-methods-how-and-when-to-use-them-2111a1b692b1)) to dispatch a thunk action that will fetch anything required for you application to run.

**Comment by xvasko** [comment]
resolved, initial state load moved to AuthenticatedPage component.
